### ISSUE TITLE
Emulate test users

### ISSUE THREAD

**Issue by julianpistorius** [cyverse/operation-sanity#17]
Try using emulation with some of these scenarios.

**Comment by c-mart** [comment]
Emulating another user breaks critical functionality like web shell and web desktop. I don't think it's a very good workaround for testing during a maintenance window. See https://pods.iplantcollaborative.org/jira/browse/ATMO-1509.

**Comment by steve-gregory** [comment]
Rather than emulate users, we have provided an explicit whitelist for users who are exempt from maintenance.
