### ISSUE TITLE
'PERSONAS' is not defined

### ISSUE THREAD

**Issue by c-mart** [cyverse/operation-sanity#8]
I don't see a project for this in JIRA, so I'm logging the issue here.

```
def before_scenario(context, scenario):
    benv.before_scenario(context, scenario)
    context.personas = PERSONAS
```

PERSONAS is not defined anywhere so this breaks all test suite runs. When I comment out `context.personas = PERSONAS`, it works.

**Comment by julianpistorius** [comment]
Confirmed. Feel free to remove that line in a PR.

**Comment by c-mart** [comment]
https://github.com/cyverse/operation-sanity/pull/9
